// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:umechat/api_key_controller.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ApiKeyController.webKey,
    appId: '1:827349109259:web:4da3156945439b1b16150e',
    messagingSenderId: '827349109259',
    projectId: 'umechat-1a276',
    authDomain: 'umechat-1a276.firebaseapp.com',
    storageBucket: 'umechat-1a276.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ApiKeyController.androidKey,
    appId: '1:827349109259:android:61653c525cab048616150e',
    messagingSenderId: '827349109259',
    projectId: 'umechat-1a276',
    storageBucket: 'umechat-1a276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ApiKeyController.iosKey,
    appId: '1:827349109259:ios:cae8d594f0684a9416150e',
    messagingSenderId: '827349109259',
    projectId: 'umechat-1a276',
    storageBucket: 'umechat-1a276.appspot.com',
    androidClientId:
        '827349109259-v2thum0336ch4l6ka02bm3cd66jg707g.apps.googleusercontent.com',
    iosClientId:
        '827349109259-cghvq3qercem18gh5rtu01e2g54933i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.umechat',
  );
}
